### ISSUE TITLE
duplicate enum registered: relay.pb.CircuitRelay_Status

### ISSUE THREAD

**Issue by florianlenz** [libp2p/go-libp2p-circuit#36]
## Issue
Hi, 

I am building a library for go-libp2p and I am getting the following error: 

```
go test -cover
2018/04/01 12:47:06 proto: duplicate proto type registered: relay.pb.CircuitRelay
2018/04/01 12:47:06 proto: duplicate proto type registered: relay.pb.CircuitRelay.Peer
panic: proto: duplicate enum registered: relay.pb.CircuitRelay_Status

goroutine 1 [running]:
github.com/florianlenz/go-libp2p-bootstrap/vendor/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/proto.RegisterEnum(0x14ecc2e, 0x1c, 0xc4204746f0, 0xc420474720)
	/Users/florian/projects/go/src/github.com/florianlenz/go-libp2p-bootstrap/vendor/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/proto/properties.go:876 +0x252
github.com/florianlenz/go-libp2p-bootstrap/vendor/gx/ipfs/QmWxHPGaiWhJkzoFa1hsYPVoKyMcd79XZTCFPF92RKv9gt/go-libp2p-circuit/pb.init.0()
	/Users/florian/projects/go/src/github.com/florianlenz/go-libp2p-bootstrap/vendor/gx/ipfs/QmWxHPGaiWhJkzoFa1hsYPVoKyMcd79XZTCFPF92RKv9gt/go-libp2p-circuit/pb/relay.pb.go:206 +0xb4
exit status 2
FAIL	github.com/florianlenz/go-libp2p-bootstrap	0.046s
make: *** [test] Error 1
```

I couldn't find / fix the error my self. 

## Reproduce
1. Clone the repo: https://github.com/florianlenz/go-libp2p-bootstrap
2. Checkout commit `7f6e8d6feeb64a939f445297a53124ef4aac07df`
3. Run `make deps`
4. Run `make install`
5. Run `make deps_hack`
6. Run `make test`

**Comment by vyzo** [comment]
Looks like you have two instances of the p2p-circuit module; there is probably something wrong with your dependency tree in the test.

**Comment by Stebalien** [comment]
@florianlenz FYI, you can run `gx deps dupes` to find duplicates and `gx deps --tree --highlight=PKG_HASH` find the duplicate package in the dependency tree.
